apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-integration-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-integration-service
  template:
    metadata:
      labels:
        app: data-integration-service
    spec:
      initContainers:
        - name: wait-for-clickhouse
          image: busybox
          command: [ 'sh', '-c', 'until nc -z clickhouse 9000; do sleep 2; done' ]
      containers:
        - name: data-integration-service
          image: shadow4733/data-integration-service:latest
          ports:
            - containerPort: 50051
          env:
            - name: CLICKHOUSE_HOST
              value: ${CLICKHOUSE_HOST}
            - name: CLICKHOUSE_PORT
              value: ${CLICKHOUSE_PORT}
            - name: CLICKHOUSE_USER
              value: ${CLICKHOUSE_USER}
            - name: CLICKHOUSE_PASSWORD
              value: ""
            - name: CLICKHOUSE_DATABASE
              value: ${CLICKHOUSE_DATABASE}
---
apiVersion: v1
kind: Service
metadata:
  name: data-integration-service
spec:
  ports:
    - port: 50051
      targetPort: 50051
  selector:
    app: data-integration-service
